import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../comps/map'

export default function Home() {
  return (
    <>
      <Head>
        <title>Expo Line Map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/monkey banana 56.png" />
      </Head>

      <header className={styles.header}>
        <Image src="/1280px-TransLink_(Vancouver)_Logo.svg.png" alt="Translink Logo" width={160} height={71}  />
        Vancouver's Expo Line
      </header>
     

      <main className={styles.main}>
        <Map/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/atran02/translink-map"
          target="_blank"
          rel="noopener noreferrer"
        >
          {/* © */}
          Angelyne Tran {' '}
          <span className={styles.logo}>
            <Image src="/monkey banana 56.png" alt="Angelyne's monkey Logo" width={28} height={28} />
          </span>
        </a>
      </footer>

    </>
  )
}
